version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      # The postgres image uses "POSTGRES_" as a prefix
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamble-blamble
  
  api:
    container_name: api
    image: node:14-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /gamble-blamble
    volumes:
      - ./:/gamble-blamble
    environment:
      PGUSER: "root"
      PGHOST: "postgres" # The other container name
      PGPASSWORD: "password"
      PGDATABASE: "gamble-blamble"
